event form
NSS-Day-Cohort-42/nutshell-lawn-artists pull request #58
Opened 2020-08-27 18:43 UTC by aring97

git fetch --all
git checkout AR-eventForm
confirm that the event form is to the groups liking

2020-08-27 19:00 UTC, mswinkels09 reviewed
Looks great!! The only thing I see is that the form renders right at page load. Not sure if we wanted it to show up only when the new event button is pressed.

2020-08-27 19:21 UTC, mgjeffries commented on src/scripts/events/EventForm.js
> +    const mobal=document.querySelector(".popup-container")
This element is a `modal` not a `mobal` please rename.

2020-08-27 19:33 UTC, mgjeffries requested changes

2020-08-27 19:33 UTC, mgjeffries commented on src/scripts/Nutshell.js
> +    eventForm()
As @mswinkels09 mentioned, the event form should not display on page load.

2020-08-27 19:33 UTC, mgjeffries commented on src/styles/main.css
> -@import "./popup.css";
As @mswinkels09 mentioned, there is already styling for the popup on the master branch. Please don't delete the import for popup.css

2020-08-27 20:40 UTC, mgjeffries approved these changes
Looks great! Thanks for working with the classes for controlling visibility.

2020-08-28 14:18 UTC, mswinkels09 approved these changes
Looks great!!

2020-08-28 14:19 UTC, merged