Article Form now renders when user clicks Create Article button.
NSS-Day-Cohort-42/nutshell-lawn-artists pull request #60
Opened 2020-08-27 20:40 UTC by heymonicakay

### Changes Made

1. Added file `articles/ArticleForm.js`
1. Updated files `articles/ArticleList.js` - included the `create article` button

### Steps to Review

```
git fetch --all
git checkout mp-article-form
```
- [ ] From Terminal > Navigate to `api` folder in repo > run `json-server -p 8088 -w database.json`
- [ ] Serve locally
- [ ] Test app functionality - Article Form should render on click and disappear when `exit` button is clicked. 
- [ ] View code > Confirm file modifications.

2020-08-27 20:45 UTC, mgjeffries approved these changes

2020-08-27 20:53 UTC, mgjeffries requested changes
Currently, when I save an article, only the title and userId are saved to the database.

2020-08-28 15:24 UTC, mgjeffries approved these changes

2020-08-28 16:52 UTC, mswinkels09 approved these changes

2020-08-28 16:56 UTC, merged